--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/HeavenPE/ExplosiveEnvoys2
branches:
- master
projects:
  ExplosiveEnvoys2:
    path: ""
    icon: "041c7919631809.562dda725a2e5-1.png"
...
